spring:
  application:
    name: MidPiece

  datasource:
    url: jdbc:postgresql://localhost:5432/Pirate
    username: postgres
    password: 12345

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect